basePath: /test
info:
  contact:
    email: xuyi@diit.cn
    name: xuyi
  description: mvt
  title: mvt
  version: "1.0"
paths:
  /mvt/{z}/{x}/{y}:
    get:
      description: mvt
      parameters:
      - description: z
        in: path
        name: z
        required: true
        type: integer
      - description: x
        in: path
        name: x
        required: true
        type: integer
      - description: "y"
        in: path
        name: "y"
        required: true
        type: integer
      responses:
        "200":
          description: '{"code":200,"data": "","msg":"success"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"data":{},"msg":"bind query err/params error"}'
          schema:
            type: string
      summary: mvt
      tags:
      - mvt
swagger: "2.0"
